function btab2(x,y)
%BTAB2  Writes out a truth-table.
%   BTAB2(x,y) where x is generated by NBC(n) or BGRAY(n),
%   and y is the boolean function generated by x, that is: y=y(x)=y(x1,...).
%
%   See also NBC2, BGRAY.
%

% Copyright (c) B. Rasmus Anthin.

fprintf \n;
for i=1:size(x,2)
   if i<10
      fprintf(' x%i ',i);
   elseif 9<i & i<100
      fprintf('x%i',i);
   end
end
fprintf('  f(x1,...)\n');

for i=1:size(x,2)+5
   fprintf('___');
end
fprintf \n;

for i=1:length(x)
   for j=1:size(x,2)
      fprintf(' %i  ',x(i,j));
   end
   fprintf('  %i',y(i));
   fprintf \n;
end
fprintf \n;